--- 
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator: 
  - name: mysql-pass
    literals: 
    - password=root
resources: 
  - efs-provisioner.yaml
  - rbac.yaml
  - storageclass+pvc.yaml
  - deploy-mysql.yaml
  - deploy-wordpress.yaml

